import type { SVGProps } from "react";

/**
 * arrow-up-right, solid.
 *
 * Exported from Figma as a bare 10×10 glyph; the design places it inset 25% in
 * a 20px box, which is the translate below. Kept out of icons/figma.tsx because
 * that file is regenerated by scripts/gen-figma-icons.mjs.
 */
export function ArrowUpRight(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        transform="translate(5 5)"
        d="M0.833333 0C0.373096 0 2.54562e-08 0.373096 2.54562e-08 0.833333C2.54562e-08 1.29357 0.373096 1.66667 0.833333 1.66667H7.15482L0.244078 8.57741C-0.0813592 8.90285 -0.0813592 9.43049 0.244078 9.75592C0.569515 10.0814 1.09715 10.0814 1.42259 9.75592L8.33333 2.84518V9.16667C8.33333 9.6269 8.70643 10 9.16667 10C9.6269 10 10 9.6269 10 9.16667V0.833333C10 0.373096 9.6269 0 9.16667 0H0.833333Z"
        fill="currentColor"
      />
    </svg>
  );
}
