import type { SVGProps } from "react";

/**
 * arrow-narrow-left, solid.
 *
 * Exported from Figma as a 15×11.67 glyph; the design insets it 20.83% top and
 * bottom, 12.5% left and right inside a 20px box, which is the translate below.
 * Kept out of icons/figma.tsx because that file is regenerated by
 * scripts/gen-figma-icons.mjs.
 */
export function ArrowNarrowLeft(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        transform="translate(2.5 4.1667)"
        d="M5.24408 0.244078C5.56951 -0.0813592 6.09703 -0.0813592 6.42246 0.244078C6.7479 0.569515 6.7479 1.09703 6.42246 1.42246L2.84499 4.99994H14.1666C14.6268 4.99994 14.9999 5.37303 14.9999 5.83327C14.9999 6.29351 14.6268 6.6666 14.1666 6.6666H2.84499L6.42246 10.2441C6.7479 10.5695 6.7479 11.097 6.42246 11.4225C6.09703 11.7479 5.56951 11.7479 5.24408 11.4225L0.244078 6.42246C-0.0813592 6.09703 -0.0813592 5.56951 0.244078 5.24408L5.24408 0.244078Z"
        fill="currentColor"
      />
    </svg>
  );
}
