import type { SVGProps } from "react";

/**
 * info-circle.
 *
 * Exported from Figma as an 18.33px glyph; the design insets it 4.17% inside a
 * 20px box, which is the translate below. Kept out of icons/figma.tsx because
 * that file is regenerated by scripts/gen-figma-icons.mjs.
 */
export function InfoCircle(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        transform="translate(0.8333 0.8333)"
        d="M16.6667 9.16667C16.6667 5.02453 13.3088 1.66667 9.16667 1.66667C5.02453 1.66667 1.66667 5.02453 1.66667 9.16667C1.66667 13.3088 5.02453 16.6667 9.16667 16.6667C13.3088 16.6667 16.6667 13.3088 16.6667 9.16667ZM8.33333 12.5V9.16667C8.33333 8.70643 8.70643 8.33333 9.16667 8.33333C9.6269 8.33333 10 8.70643 10 9.16667V12.5C10 12.9602 9.6269 13.3333 9.16667 13.3333C8.70643 13.3333 8.33333 12.9602 8.33333 12.5ZM9.1748 5C9.63504 5 10.0081 5.3731 10.0081 5.83333C10.0081 6.29357 9.63504 6.66667 9.1748 6.66667H9.16667C8.70643 6.66667 8.33333 6.29357 8.33333 5.83333C8.33333 5.3731 8.70643 5 9.16667 5H9.1748ZM18.3333 9.16667C18.3333 14.2293 14.2293 18.3333 9.16667 18.3333C4.10406 18.3333 0 14.2293 0 9.16667C0 4.10406 4.10406 0 9.16667 0C14.2293 0 18.3333 4.10406 18.3333 9.16667Z"
        fill="currentColor"
      />
    </svg>
  );
}
